version: "3.9"
   
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
      args:
        ADMIN_EMAIL: "${ADMIN_EMAIL}"
        ADMIN_USERNAME: "${ADMIN_USERNAME}"
        ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    restart: always
    volumes:
      - web_data:/var/lib/web
      - static_volume:/home/app/web/static
    # ports:
      # - "${WEB_PORT}:8080"
    expose:
      - 8080
  
  nginx:
    build: ./nginx
    ports:
      - ${WEB_PORT}:8080
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web

volumes:
  static_volume:
  web_data:
    driver: local